apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: pds-demo
stringData:
    POSTGRES_DATABASE: keycloak
    POSTGRES_EXTERNAL_ADDRESS: localhost
    POSTGRES_EXTERNAL_PORT: '5432'
    POSTGRES_PASSWORD: password
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: "true"
    POSTGRES_USERNAME: pds
    SSLMODE: disable
type: Opaque