apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
      app: sso
  name: example-rhsso
  namespace: pds-demo
spec:
  externalDatabase:
    enabled: true
  instances: 1
  externalAccess:
    enabled: True  