apiVersion: v1
kind: Secret
metadata:
    name: fruits-app-secret
    namespace: pds-demo
stringData:
  quarkus.datasource.db-kind: postgresql
  quarkus.datasource.username: pds
  quarkus.datasource.password: password
  quarkus.datasource.jdbc.url: jdbc:postgresql://localhost:5432/fruit
  quarkus.hibernate-orm.database.generation: update
type: Opaque